name: Vault
version: ${project.version}
main: net.milkbowl.vault.Vault
description: Vault service abstraction for Folia.
authors: [cereal, Sleaker, mung3r]
website: ${project.url}
api-version: '26.1.2'
folia-supported: true
load: STARTUP
